-- Events table
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  created_at timestamptz default now()
);

-- Media metadata
create table if not exists public.media (
  id bigint generated by default as identity primary key,
  code text references public.events(code) on delete cascade,
  path text not null,
  mime text,
  created_at timestamptz default now()
);

alter table events enable row level security;
alter table media enable row level security;
